### ISSUE TITLE
More friendly geneset names?

### ISSUE THREAD

**Issue by vincerubinetti** [biothings/mygeneset.info#25]
There may be opportunities to improve the human readability of the geneset names. Here are some examples of less-than-ideal names:

BIOCARTA KERATINOCYTE PATHWAY
ALLOGRAFT_REJECTION
https://www.genome.jp/kegg-bin/show_pathway?hsa05330
https://www.genome.jp/dbget-bin/www_bget?hsa05330

@cgreene found these examples, but I'm sure there are many more. Cases where the actual source has a more human friendly name, like "Allograft Rejection", but isn't being used for some reason.

I could add something to the frontend to format these more nicely, though the user would still have to search for the less-human friendly name to find a match.

**Comment by ravila4** [comment]
The latest data release should have friendly name fields.
Most of the names with caps and underscore chars were from the msigdb database and that is fixed with a new parser.

The examples mentioned above:
http://mygeneset.info/v1/geneset/WP_ALLOGRAFT_REJECTION
http://mygeneset.info/v1/geneset/BIOCARTA_KERATINOCYTE_PATHWAY
